// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cgqaqooqfrdwnesqvnfz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNncWFxb29xZnJkd25lc3F2bmZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzNjM4NjksImV4cCI6MjA2NTkzOTg2OX0.QrekNjGf2DI7PxDT9YN1okXBgxVkZ5QWtlPv2Uk6PJE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);