// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pnxigppewlsksfbmtbba.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBueGlncHBld2xza3NmYm10YmJhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxNzYxNzUsImV4cCI6MjA2NDc1MjE3NX0.4lkYJPjUazcJ6IbGT--HVZGz3lfTMBigM-Wi3Xk4_fk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);