// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zyrbkxkxdznyhrpudhrk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp5cmJreGt4ZHpueWhycHVkaHJrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MjA5NjgsImV4cCI6MjA2NTQ5Njk2OH0.iq9Guu8t_0Z3dtqtm-q0lCOAEwBTXACfZ79FPoOKQoc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);